root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ./..."
  include_ext = ["go", "mod", "sum", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "postgres-data", "redis-data"]
  delay = 1000

[log]
  time = true
  color = true

[screen]
  clear_on_rebuild = true
